main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', QuizListView.as_view(), name='main-view'),
    path('<pk>', quiz_view, name='quiz-view'),
    path('<pk>/data', quiz_data_view, name='quiz-data-view'),
    path('<pk>/save', save_quiz_view, name='save-view'),
]

quizz/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns
    
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
import random

# Create your models here.

DIFF_CHOISES = (
	('easy', 'easy'),
	('medium', 'medium'),
	('hard', 'hard'),
)

class Quiz(models.Model):
	name = models.CharField(max_length=120)
	topic = models.CharField(max_length=120)
	number_of_questions = models.IntegerField()
	time = models.IntegerField(help_text="duration of the quiz in minutes")
	required_score_to_pass = models.IntegerField(help_text="required score in %")
	difficulty = models.CharField(max_length=6, choices=DIFF_CHOISES)

	class Meta:
		verbose_name_plural = 'Quizes'
		pass

	def __str__(self):
		return f"{self.name}-{self.topic}"

	def get_questions(self):
		questions = list(self.question_set.all())
		random.shuffle(questions)
		
		return questions[:self.number_of_questions]

questions/models.py
from django.db import models
from main.models import Quiz

# Create your models here.
class Question(models.Model):
	text = models.CharField(max_length=200)
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return str(self.text)

	def get_answers(self):
		return self.answer_set.all()


class Answer(models.Model):
	text = models.CharField(max_length=200)
	correct = models.BooleanField(default=False)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	created = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return f"question: {self.question.text}, answer: {self.text}, correct: {self.correct}"

results/models.py
from django.db import models
from main.models import Quiz
from django.contrib.auth.models import User

# Create your models here.
class Result(models.Model):
	quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	score = models.FloatField()

	def __str__(self):
		return str(self.pk)

main/views.py
from django.shortcuts import render
from .models import Quiz
from django.views.generic import ListView
from django.http import JsonResponse
from results.models import *
from questions.models import *

class QuizListView(ListView):
    model = Quiz 
    template_name = 'quizes/main.html'

def quiz_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    return render(request, 'quizes/quiz.html', {'obj': quiz})

def quiz_data_view(request, pk):
	quiz = Quiz.objects.get(pk=pk)
	questions = []
	for q in quiz.get_questions():
		answers = []
		for a in q.get_answers():
			answers.append(a.text)
		questions.append({str(q): answers})

	return JsonResponse({
		'data':questions,
		'time':quiz.time,
	})

def save_quiz_view(request, pk):
	# print(request.POST)
	if request.is_ajax():
		questions = []
		data = request.POST
		data_ = dict(data.lists())

		data_.pop('csrfmiddlewaretoken')

		for k in data_.keys():
			print('key: ', k)
			question = Question.objects.get(text=k)
			questions.append(question)
		print(questions)

		user = request.user
		quiz = Quiz.objects.get(pk=pk)

		score = 0
		multipliyer = 100 / quiz.number_of_questions
		results = []
		correct_answer = None

		for q in questions:
			a_selected = request.POST.get(q.text)

			if a_selected != "":
				question_answers = Answer.objects.filter(question=q)
				for a in question_answers:
					if a_selected == a.text:
						if a.correct:
							score += 1
							correct_answer = a.text
					else:
						if a.correct:
							correct_answer = a.text

				results.append({str(q): {'correct_answer': correct_answer, 'answered':a_selected}})
			else:
				results.append({str(q): 'not answered'})

		score_ = score * multipliyer
		Result.objects.create(quiz=quiz, user=user, score=score_)

		if score_ >= quiz.required_score_to_pass:
			return JsonResponse({'passed':True, 'score':score_, 'results':results})
		else:
			return JsonResponse({'passed':False, 'score':score_, 'results':results})
	return JsonResponse({'text':'works'})

questions/views.py
from django.shortcuts import render

# Create your views here.

results/views.py
from django.shortcuts import render

# Create your views here.

main/templates/quizes/main.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static 'quizes/main.js' %}" defer></script> 
{% endblock scripts %}

{% block title %}
home
{% endblock title %}

{% block content %}

<!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div style="background-color: #30445C;" class="modal-header">
        <h5 class="modal-title text-white" id="exampleModalLabel">Start?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div style="background-color: #242B3E" class="modal-body" id="modal-body-confirm"></div>
      <div style="background-color: #30445C;" class="modal-footer">
        <button style="border-radius: 10px;" type="button" class="btn btn-danger" data-dismiss="modal">No</button>
        <button style="border-radius: 10px;" type="button" id="start-button" class="btn btn-success">Yes</button>
      </div>
      
    </div>
  </div>
</div>

<center>
  <div class="h1 text-light mt-2"><b style="color: #ED851B">Quiz List</b></div>
  <h3 class="text-light mt-4">Welcome</h3>
  <p style="color: #c1c1c1;" class="mt-3">Lorem, ipsum dolor sit, amet consectetur adipisicing elit. Exercitationem id natus at, mollitia ad fuga aperiam accusamus porro, quas. Iure, maxime? Minus, quos ea illum quasi commodi dignissimos perspiciatis voluptate? Minus, quos ea illum quasi?</p>
</center>

<hr>
<br>
<div style="width: 55%" class="container">
  <div class="row">
      {% for obj in object_list %}
        <div class="col-6">
          <a id="btn" style='text-decoration: none; '
            class="btn btn-link modal-button ml-3"
            data-pk="{{obj.pk}}"
            data-quiz="{{obj.name}}"
            data-questions="{{obj.number_of_questions}}"
            data-difficulty="{{obj.difficulty}}"
            data-time="{{obj.time}}"
            data-pass = "{{obj.required_score_to_pass}}"
            data-toggle="modal"
            data-target="#quizStartModal">
            {{obj.name}}
          </a>
          <br>
          <br>
        </div>
        <hr>
      {% endfor %}
  </div>

</div>




<style>
  b{
    color: #E78230;
  }
  li{
    color: #CDCDCD;
    font-family: sans-serif;
  }
  .h5{
    color: #D5D5D5;
  }
  #btn{
    width: 220px; 
    height: 50px;
    border-radius: 30px;
    background-color: #E78230;
    color: whitesmoke;
  }
  #btn:hover{
    background-color: #fff;
    color: #E78230;
    box-shadow: 0 0 8px #30445C, 0 0 16px #30445C, 0 0 24px #30445C;
    width: 238px;
    transition: all 0.5s;
  }
</style>

{% endblock content %}

main/templates/quizes/quiz.html
{% extends "base.html" %}
{% load static %}

{% block scripts %}
    <script src="{% static "quizes/quiz.js" %}" defer></script>
{% endblock scripts %}

{% block title %}
{{obj.name}}
{% endblock title %}

{% block content %}



<form id="quiz-form" class="mt-3 mb-3">
    {% csrf_token %}
    <div style="border-radius: 15px;" class="card">
        <div class="card-body m-2">
            <center><h2 style="color: #CDCDCD;"><b>{{obj.name}}</b></h2></center>
            <br>
            <br>
            <div class="container ml-4">
                <div class="row ml-5">
                    <div class="col-lg-4">
                        <h5 style="color: #17C0A8;" class="mt-3">Score to pass: {{obj.required_score_to_pass}}%</h5>
                    </div>
                    <div class="col-lg-4">
                        <a id="back" href="{% url 'main:main-view' %}" class="btn">Go back</a>
                    </div>
                    <div class="col-lg-4">
                        <div style="width: 75px; height: 50px;background-color: #17C0A8;border-radius: 30px;" class="bgc ml-5">
                        <div class="col text-right" id="timer-box"></div>
                        </div>
                    </div>
                </div>
            </div>
            
            <br>
            <div id="quiz-box"></div>
            <br>
            <br>
            <button id="sb" type="submit" class="btn mt-3">Save</button>
        </div>
    </div>
    
</form>
<div id="score-box"></div>
<br>
<div id="result-box"></div>

<style>
    b{
        color:  #DEDEDE;
    }
    lable{
        color: #fff;
    }
    .card{
        background-color: #30445C;
    }
    #score-box{
        color: white;
        font-size: bold
    }
    #qcard{
        border-radius: 30px;
        background-color: #2B3D53;
    }
    #qcard:hover{
        border: 1px solid #E78230;
        transition: all 0.5s;
        box-shadow: 0 0 6px #E78230, 0 0 12px #E78230, 0 0 18px #E78230;
    }
    #sb{
        background-color: #17C0A8;
        color: white;
        width: 100%; 
        height: 43px;
    }
    #sb:hover{
        transition: all 0.5s;
        box-shadow: 0 0 4px #72A1DB, 0 0 8px #72A1DB, 0 0 12px #72A1DB;
    }
    #back{
        background-color: #E78230; 
        color: white; 
        width: 200px; 
        height: 50px;
        margin-right: 60px;
        border-radius: 30px;
    }
    #timer-box{
        padding-top: 10px;
    }
</style>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- bootstrap -->
	<link rel="stylesheet" href="{% static '/css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static '/css/bootstrap.min.css' %}">
	<!-- jquery -->
	<script src="{% static '/js/jquery.js' %}"></script>	
	<!-- custom css & js -->
	<link rel="stylesheet" href="{% static '/css/style.css' %}">

	{% block scripts %}
	{% endblock scripts %}

	<title>{% block title %}{% endblock title %}</title>
</head>
<body style="background-color: #242B3E">
	<div class="container mt-3">
		{% block content %}
		{% endblock content %}
	</div>
	
	<script src="{% static '/js/bootstrap.js' %}"></script>
	<script src="{% static '/js/bootstrap.min.js' %}"></script>
</body>
</html>